import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("data/processed/HR_Analytics_Final.csv")

gender_count = df["Gender"].value_counts()
plt.figure(figsize=(6,5))
gender_count.plot(kind="bar")
plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/gender_distribution.png", dpi=300)
plt.show()

department_count = df["Department"].value_counts()
plt.figure(figsize=(8,5))
department_count.plot(kind="bar")
plt.title("Department Distribution")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/department_distribution.png", dpi=300)
plt.show()

jobrole_count = df["JobRole"].value_counts()
plt.figure(figsize=(10,6))
jobrole_count.plot(kind="bar")
plt.title("Job Role Distribution")
plt.xlabel("Job Role")
plt.ylabel("Number of Employees")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("images/demographics/jobrole_distribution.png", dpi=300)
plt.show()

attrition_count = df["Attrition"].value_counts()
plt.figure(figsize=(6,5))
attrition_count.plot(kind="bar")
plt.title("Attrition Distribution")
plt.xlabel("Attrition")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/attrition_distribution.png", dpi=300)
plt.show()

plt.figure(figsize=(8,5))
df["Age"].plot(kind="hist", bins=10)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/age_distribution.png", dpi=300)
plt.show()

education_count = df["Education"].value_counts().sort_index()
plt.figure(figsize=(7,5))
education_count.plot(kind="bar")
plt.title("Education Level Distribution")
plt.xlabel("Education Level")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/education_distribution.png", dpi=300)
plt.show()

marital_count = df["MaritalStatus"].value_counts()
plt.figure(figsize=(7,5))
marital_count.plot(kind="bar")
plt.title("Marital Status Distribution")
plt.xlabel("Marital Status")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/demographics/marital_status_distribution.png", dpi=300)
plt.show()

plt.figure(figsize=(8,5))
df["MonthlyIncome"].plot(kind="hist", bins=15)
plt.title("Monthly Income Distribution")
plt.xlabel("Monthly Income")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/salary/monthly_income_distribution.png", dpi=300)
plt.show()

salary_count = df["SalarySlab"].value_counts()
plt.figure(figsize=(7,5))
salary_count.plot(kind="bar")
plt.title("Salary Slab Distribution")
plt.xlabel("Salary Slab")
plt.ylabel("Number of Employees")
plt.tight_layout()
plt.savefig("images/salary/salary_slab_distribution.png", dpi=300)
plt.show()